import {
	ConsentStates,
	DealStatuses,
	type ConsentState,
	type DealStatusName
} from '$lib/enums/deal-status';
import type { ClaimableDeal, ConsentKey, Deal, DealSide, DealStatusKey } from '$lib/types/deal';
import { fromNullable } from '@dfinity/utils';
import type { Principal } from '@icp-sdk/core/principal';

/**
 * Variants generated by `@icp-sdk/bindgen` look like `{ Funded: null }`
 * (single-key tagged objects). This helper unwraps the discriminator key.
 */
const variantKey = <T extends string>(variant: Record<T, unknown>): T =>
	Object.keys(variant)[0] as T;

export const dealStatus = (
	deal: Pick<Deal, 'status'> | Pick<ClaimableDeal, 'status'>
): DealStatusName => variantKey<DealStatusKey>(deal.status) as DealStatusName;

export const consentState = (consent: Deal['payer_consent']): ConsentState =>
	variantKey<ConsentKey>(consent) as ConsentState;

export const isTerminal = (status: DealStatusName): boolean =>
	status === DealStatuses.Settled ||
	status === DealStatuses.Refunded ||
	status === DealStatuses.Cancelled ||
	status === DealStatuses.Rejected;

export const isExpired = (deal: Pick<Deal, 'expires_at_ns'>, nowNs: bigint): boolean =>
	deal.expires_at_ns <= nowNs;

/**
 * Which side of the deal is `principal` on? Returns `'unknown'` when the
 * principal matches neither party — used by the public claim preview.
 */
export const sideOf = (
	deal: Pick<Deal, 'payer' | 'recipient'>,
	principal: Principal | undefined
): DealSide => {
	if (principal === undefined) {
		return 'unknown';
	}

	const payer = fromNullable(deal.payer);
	const recipient = fromNullable(deal.recipient);

	if (payer?.toText() === principal.toText()) {
		return 'payer';
	}

	if (recipient?.toText() === principal.toText()) {
		return 'recipient';
	}

	return 'unknown';
};

/**
 * Whether both parties have explicitly accepted the deal terms.
 */
export const isFullyConsented = (
	deal: Pick<Deal, 'payer_consent' | 'recipient_consent'>
): boolean =>
	consentState(deal.payer_consent) === ConsentStates.Accepted &&
	consentState(deal.recipient_consent) === ConsentStates.Accepted;
