/**
 * Variants generated by `@icp-sdk/bindgen` look like `{ Funded: null }`
 * (single-key tagged objects). This helper unwraps the discriminator
 * key so app code can `switch` on a plain string.
 *
 * Lives in its own module so dispute / deal / arbitrator utils can
 * share the helper without cross-importing each other.
 */
export const variantKey = <T extends string>(variant: Record<T, unknown>): T =>
	Object.keys(variant)[0] as T;
