import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
	js.configs.recommended,
	...tseslint.configs.recommended,
	...svelte.configs['flat/recommended'],
	prettier,
	...svelte.configs['flat/prettier'],
	{
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node
			}
		}
	},
	{
		files: ['**/*.svelte'],
		languageOptions: {
			parserOptions: {
				parser: tseslint.parser
			}
		}
	},
	{
		files: ['*.ts'],
		rules: {
			'prefer-const': 'error'
		}
	},
	{
		ignores: [
			'build/',
			'.svelte-kit/',
			'dist/',
			'static/',
			// Generated by `npm run did` (@icp-sdk/bindgen) — must not be linted.
			'src/declarations/**/*.idl.js',
			'src/declarations/**/*.idl.d.ts',
			'src/declarations/escrow/escrow.d.ts'
		]
	},
	{
		rules: {
			'@typescript-eslint/consistent-type-definitions': 'error',
			'@typescript-eslint/no-inferrable-types': 'error',
			// '@typescript-eslint/no-unnecessary-type-assertion': 'error',
			'@typescript-eslint/no-unused-vars': [
				'warn',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_'
				}
			],
			// '@typescript-eslint/prefer-nullish-coalescing': 'error',
			// '@typescript-eslint/prefer-reduce-type-parameter': 'error',
			'arrow-body-style': ['warn', 'as-needed'],
			curly: 'error',
			'no-console': ['error', { allow: ['error', 'warn'] }],
			'no-continue': 'warn',
			'no-delete-var': 'error',
			'no-else-return': ['warn', { allowElseIf: false }],
			'no-unused-vars': 'off',
			'prefer-template': 'error',
			'require-await': 'error',
			// External / user-supplied URLs are bound to `<a href>` here; the
			// SvelteKit `resolve()` helper is meant for in-app navigation.
			'svelte/no-navigation-without-resolve': 'off'
		}
	},
	{
		plugins: {
			import: importPlugin
		},
		rules: {
			'import/no-duplicates': ['error', { 'prefer-inline': true }],
			'import/no-relative-parent-imports': 'error'
		}
	},
	{
		files: ['**/*.svelte', '*.svelte'],
		rules: {
			'import/order': ['error', { alphabetize: { order: 'asc' } }],
			'import/no-duplicates': ['error', { 'prefer-inline': true }]
		}
	},
	{
		files: ['scripts/**/*.ts'],
		rules: {
			'no-console': 'off'
		}
	}
);
