/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Profile {
	updated_at: bigint;
	username: string;
	owner: Principal;
	avatar_url: [] | [string];
	name: string;
	surname: string;
	/**
	 * Nanoseconds since the epoch, set by the canister.
	 */
	created_at: bigint;
}
export type Result = { Ok: Profile } | { Err: string };
/**
 * What a caller may set. The owner and the timestamps are not in here: they
 * are derived from the caller and the clock, never trusted from input.
 */
export interface SetProfile {
	username: string;
	avatar_url: [] | [string];
	name: string;
	surname: string;
}
export interface _SERVICE {
	/**
	 * Publicly readable, as the Juno collection was: any caller can resolve a
	 * profile from a principal.
	 */
	get_profile: ActorMethod<[Principal], [] | [Profile]>;
	/**
	 * Creates or replaces the caller's own profile.
	 */
	set_profile: ActorMethod<[SetProfile], Result>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
