/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const Profile = IDL.Record({
		updated_at: IDL.Nat64,
		username: IDL.Text,
		owner: IDL.Principal,
		avatar_url: IDL.Opt(IDL.Text),
		name: IDL.Text,
		surname: IDL.Text,
		created_at: IDL.Nat64
	});
	const SetProfile = IDL.Record({
		username: IDL.Text,
		avatar_url: IDL.Opt(IDL.Text),
		name: IDL.Text,
		surname: IDL.Text
	});
	const Result = IDL.Variant({ Ok: Profile, Err: IDL.Text });

	return IDL.Service({
		get_profile: IDL.Func([IDL.Principal], [IDL.Opt(Profile)], []),
		set_profile: IDL.Func([SetProfile], [Result], [])
	});
};

export const init = ({ IDL }) => {
	return [];
};
