/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

/**
 * Arguments for accepting (claiming) a funded deal.
 */
export interface AcceptDealArgs {
	/**
	 * Claim code required for open (unbound-recipient) deals. Must match the
	 * code generated at deal creation. Not required when the caller is the
	 * deal's bound recipient.
	 */
	claim_code: [] | [string];
	/**
	 * Identifier of the deal to accept.
	 */
	deal_id: bigint;
}
export type AcceptDealResult = { Ok: DealView } | { Err: EscrowError };
export interface Account {
	owner: Principal;
	subaccount: [] | [Uint8Array];
}
/**
 * Arguments for `admin_register_arbitrator`.
 *
 * Idempotent — calling for an already-registered principal returns
 * the existing profile, with two side effects on every successful
 * call (regardless of prior status):
 *
 * - Status is set to `Active` (reactivating `Suspended` / `Deregistered` profiles, no-op for
 * already-`Active`).
 * - `registered_by` is refreshed to the calling controller, so the audit trail reflects the most
 * recent curation event.
 *
 * Score-related counters and `registered_at_ns` are preserved across
 * re-registration.
 */
export interface AdminRegisterArbitratorArgs {
	principal: Principal;
}
export type AdminRegisterArbitratorResult = { Ok: ArbitratorProfile } | { Err: EscrowError };
/**
 * Arguments for `admin_set_arbitrator_status`.
 *
 * All transitions are allowed (Active ↔ Suspended ↔ Deregistered).
 * A self-transition (e.g. `Active → Active`) is a no-op success.
 * `Deregistered → Active` reactivates a profile previously removed
 * — but unlike `admin_register_arbitrator` it does NOT refresh
 * `registered_by` (the audit trail still points at the original
 * admin that first added the arbitrator) and does NOT re-run the
 * `validate_arbitrator_principal` check (the principal was already
 * validated at original registration time). To both reactivate AND
 * refresh the audit trail, use `admin_register_arbitrator` instead.
 */
export interface AdminSetArbitratorStatusArgs {
	status: ArbitratorStatus;
	principal: Principal;
}
/**
 * Arguments for `admin_treasury_balance` — the controller-only
 * query that returns how much of `asset` is currently sitting in
 * the canister's treasury subaccount (where every deal's
 * `creation_fee` accumulates). One asset per call so the
 * controller can iterate ledgers explicitly.
 */
export interface AdminTreasuryBalanceArgs {
	/**
	 * Settlement asset to query. Today only [`Asset::Icrc`]; the
	 * query reaches the underlying ledger via
	 * [`crate::ledger::balance_of`].
	 */
	asset: Asset;
}
export type AdminTreasuryBalanceResult = { Ok: bigint } | { Err: EscrowError };
/**
 * Arguments for `admin_treasury_withdraw` — the controller-only
 * drain endpoint. Pulls `amount` of `asset` from the treasury
 * subaccount and `icrc1_transfer`s it to `to`. Caller is
 * responsible for sizing `amount` against the live treasury
 * balance (`admin_treasury_balance`); under-funded withdrawals
 * surface as `EscrowError::TransferFailed` from the ledger.
 */
export interface AdminTreasuryWithdrawArgs {
	/**
	 * Destination account. Typically a controller's own account
	 * or a downstream treasury / ops wallet.
	 */
	to: Account;
	asset: Asset;
	/**
	 * Amount to transfer in `asset`'s base units. Must be
	 * `> ledger_fee` (the ledger burns one fee per transfer).
	 */
	amount: bigint;
}
/**
 * Public profile of a registered arbitrator.
 *
 * Score-related fields follow these rules:
 *
 * | Outcome                | Voter type              | `assigned` | `voted` | `with_majority` |
 * | ---------------------- | ----------------------- | ---------- | ------- | --------------- |
 * | `Settled` / `Refunded` | non-abstain w/ majority | +1         | +1      | +1              |
 * | `Settled` / `Refunded` | non-abstain vs majority | +1         | +1      | +0              |
 * | `Settled` / `Refunded` | abstain                 | +1         | +0      | +0              |
 * | `NoQuorum`             | any (incl. non-abstain) | +1         | +0      | +0              |
 * | `Withdrawn`            | any                     | +1         | +0      | +0              |
 *
 * `NoQuorum` and `Withdrawn` deliberately don't update `voted` or
 * `with_majority` — there's no on-canister verdict against which to
 * score votes, and counting them would create a perverse incentive
 * to abstain on hard-to-quorum disputes.
 *
 * `score` is computed via [`ArbitratorProfile::compute_score`] and is
 * `None` until `disputes_voted >= MIN_VOTES_FOR_SCORE`.
 *
 * Human-readable description (name, jurisdiction, languages, contact,
 * etc.) is intentionally **not** stored on-canister — it lives in the
 * consuming app's off-chain directory keyed by `principal`. The
 * canister only carries data its own logic actually reads.
 */
export interface ArbitratorProfile {
	status: ArbitratorStatus;
	principal: Principal;
	registered_at_ns: bigint;
	/**
	 * Total disputes the arbitrator was selected for.
	 */
	disputes_assigned: number;
	/**
	 * 0–100 reliability score, or `None` until enough scored votes
	 * accumulate (`disputes_voted >= MIN_VOTES_FOR_SCORE`).
	 */
	score: [] | [number];
	/**
	 * Disputes the arbitrator submitted a non-abstain vote on, excluding
	 * `NoQuorum` and `Withdrawn` outcomes.
	 */
	disputes_voted: number;
	/**
	 * Disputes where the arbitrator's non-abstain vote matched the
	 * eventual majority. `NoQuorum` / `Withdrawn` outcomes never
	 * increment this counter.
	 */
	disputes_with_majority: number;
	/**
	 * The controller principal that registered this arbitrator. Audit
	 * trail for the curated registration model.
	 */
	registered_by: Principal;
}
/**
 * Lifecycle status of an arbitrator. Transitions:
 *
 * ```text
 * (unregistered) ──admin_register──▶ Active ──admin──▶ Suspended
 * │                │
 * └──self──▶ Deregistered ◀──admin──┘
 * │
 * └──admin_register──▶ Active (reactivation)
 * ```
 *
 * `Suspended` and `Deregistered` arbitrators cannot be selected for
 * new disputes, but in-flight assignments are honoured — a non-vote
 * from a non-Active panel member counts as `Vote::Abstain` at
 * finalize time. Both statuses are recoverable: admin can flip the
 * arbitrator back to `Active` via `admin_set_arbitrator_status`, and
 * an `admin_register_arbitrator` call on a `Deregistered` profile
 * reactivates it (idempotent).
 */
export type ArbitratorStatus = { Deregistered: null } | { Active: null } | { Suspended: null };
/**
 * A settlement asset accepted by the escrow canister.
 *
 * Always interrogate via the typed accessors (e.g. [`Asset::as_icrc`])
 * rather than pattern-matching directly — this keeps service code
 * resilient to future variant additions.
 */
export type Asset = {
	/**
	 * An ICRC-1 / ICRC-2 token identified by its ledger
	 * [`Principal`] on the Internet Computer.
	 */
	Icrc: Principal;
};
/**
 * Arguments for cancelling an unfunded deal.
 */
export interface CancelDealArgs {
	/**
	 * Identifier of the deal to cancel.
	 */
	deal_id: bigint;
}
/**
 * Arguments for `cast_vote`.
 *
 * Caller must be on the dispute's panel and currently `Active`.
 * Allowed only during the open voting window
 * (`evidence_deadline_ns <= now_ns < voting_deadline_ns`). Latest-wins
 * — calling repeatedly during the window updates the recorded vote.
 */
export interface CastVoteArgs {
	vote: Vote;
	dispute_id: bigint;
}
export type CastVoteResult = { Ok: DisputeView } | { Err: EscrowError };
/**
 * Reduced view for public claim pages — does not expose payer, claim code,
 * or internal fields.
 */
export interface ClaimableDealView {
	/**
	 * Unique deal identifier.
	 */
	id: bigint;
	/**
	 * Current lifecycle status of the deal.
	 */
	status: DealStatus;
	/**
	 * Optional short title.
	 */
	title: [] | [string];
	/**
	 * Settlement asset for this deal. Today always
	 * [`Asset::Icrc`].
	 */
	asset: Asset;
	/**
	 * Optional note or message.
	 */
	note: [] | [string];
	/**
	 * Escrowed token amount.
	 */
	amount: bigint;
	/**
	 * Nanosecond UTC timestamp after which the deal expires.
	 */
	expires_at_ns: bigint;
	/**
	 * Whether a recipient principal has already been bound to this deal.
	 */
	is_recipient_bound: boolean;
}
/**
 * Global configuration for the Escrow canister.
 */
export interface Config {
	/**
	 * Per-deal escrow service fee, in the deal's token. Charged on
	 * every terminal state. Defaults to [`DEFAULT_ESCROW_FEE`].
	 * Snapshotted into each `Deal.fees.escrow_fee` at `create_deal`
	 * time; subsequent `update_config` changes do not retroactively
	 * alter in-flight deals.
	 */
	escrow_fee: bigint;
	/**
	 * Per-deal anti-spam creation fee. Pulled from the creator at
	 * `create_deal` time on bound deals (recipient is `Some`) and
	 * routed to the canister's treasury subaccount. Tips
	 * (`recipient = None`) skip it entirely — there's no
	 * counterparty to spam-harass. Defaults to
	 * [`DEFAULT_CREATION_FEE`]. Snapshotted into each
	 * `Deal.fees.creation_fee` at create time; subsequent
	 * `update_config` changes do not retroactively alter
	 * in-flight deals.
	 */
	creation_fee: bigint;
	/**
	 * Admin-tunable dispute parameters. Fallback is whole-struct
	 * (`update_config` replaces the entire `DisputeConfig` — there
	 * is no per-field "leave unchanged" merge mechanism).
	 */
	dispute_config: DisputeConfig;
}
export type Consent = { Rejected: null } | { Accepted: null } | { Pending: null };
/**
 * Arguments for creating a new deal.
 *
 * If both `payer` and `recipient` are `None`, the caller defaults to payer
 * and the recipient is bound on first acceptance (tip / share-link flow).
 * If neither resolved party is the caller, the call is rejected. The
 * caller's consent is automatically set to `Accepted`; the counterparty's
 * consent starts as `Pending`.
 */
export interface CreateDealArgs {
	/**
	 * Optional short title displayed on claim pages.
	 */
	title: [] | [string];
	/**
	 * Settlement asset for this deal. Today the canister only
	 * handles ICRC-1 / ICRC-2 ledgers, so clients pass the asset
	 * as the `Icrc` variant — at the Candid boundary that's
	 * `asset = variant { Icrc = <ledger principal> }` (and
	 * `Asset::Icrc(<ledger principal>)` from Rust). The variant
	 * exists so future settlement domains (EVM, Solana, …) can
	 * be added without renaming this field.
	 */
	asset: Asset;
	/**
	 * Optional per-deal arbitrator panel size. If `Some(n)`, any
	 * dispute opened on this deal will use `n` arbitrators regardless
	 * of subsequent `DisputeConfig.panel_size` changes — the deal
	 * terms are a contract at create time. `None` falls back to
	 * `DisputeConfig.panel_size` at `open_dispute` time.
	 *
	 * Validation at create time: must be odd, must be within
	 * `[DisputeConfig.min_panel_size, DisputeConfig.max_panel_size]`.
	 * Out-of-range values return `EscrowError::PanelSizeOutOfRange`.
	 */
	panel_size: [] | [number];
	/**
	 * Optional note or message attached to the deal.
	 */
	note: [] | [string];
	/**
	 * Optional recipient principal. If `None`, the recipient is bound on first
	 * acceptance (QR / share-link flow).
	 */
	recipient: [] | [Principal];
	/**
	 * Optional payer principal. If `None`, defaults to the caller when the
	 * caller is not the recipient.
	 */
	payer: [] | [Principal];
	/**
	 * Token amount to escrow (must be > 0). Denominated in the
	 * base units of the deal's `asset` (e.g. e8s for ICP).
	 */
	amount: bigint;
	/**
	 * Nanosecond UTC timestamp after which the deal expires and becomes reclaimable.
	 */
	expires_at_ns: bigint;
}
/**
 * Per-deal fee snapshot taken at `create_deal` time.
 *
 * Every fee the canister will charge against this deal over its
 * lifetime is locked here so that subsequent `update_config` calls
 * cannot retroactively alter the agreed economics. Same pattern as
 * `Deal.panel_size`: the deal terms are a contract at create time.
 *
 * `Default` is implemented for test ergonomics — production code
 * always builds a `DealFees` via `services::deals::compute_deal_fees`.
 */
export interface DealFees {
	/**
	 * Escrow service fee in the deal's token. Charged on every
	 * terminal state (`Settled`, `Refunded`, `Cancelled` with a
	 * committed reserve, `Rejected` with a committed reserve,
	 * `ArbitratedSettled`, `ArbitratedRefunded`). Snapshot of
	 * `Config.escrow_fee` at `create_deal` time.
	 */
	escrow_fee: bigint;
	/**
	 * Anti-spam creation fee in the deal's token. Pulled from the
	 * creator at `create_deal` time and routed to the canister's
	 * controller-controlled treasury subaccount
	 * (`subaccounts::TREASURY_SUBACCOUNT`). Always forfeited —
	 * never refunded on any terminal — so a creator who spams
	 * deals at counterparties they know will reject still pays
	 * the per-deal stamp. Snapshot of `Config.creation_fee` at
	 * create time. Set to `0` for tip flows (no bound counterparty
	 * to spam, so no deterrent needed).
	 */
	creation_fee: bigint;
	/**
	 * Reduced-fee percentage the arbitrator panel receives when
	 * the parties resolve out-of-band via `withdraw_dispute`.
	 * Snapshot of `DisputeConfig.withdraw_fee_pct` at create time.
	 */
	withdraw_fee_pct: number;
	/**
	 * Per-party dispute reserve. Each party pre-commits this amount
	 * before the deal can be `Funded`. Refunded on happy-path
	 * terminal states (minus one `ledger_fee` per outgoing refund
	 * transfer); consumed by the arbitrator panel on
	 * `Disputed → ArbitratedX`. Snapshot of
	 * `compute_arbitration_fee(amount, DisputeConfig) / 2` at
	 * create time.
	 */
	dispute_reserve_per_party: bigint;
	/**
	 * Ledger `icrc1_fee` value at create time, in the deal's
	 * token. RECORD ONLY — never used for arithmetic. Every
	 * actual transfer re-queries the live fee via
	 * `ledger::fee`. Snapshotted so the audit trail can answer
	 * "what was the user shown at create time?" even if the
	 * ledger later changes its fee. Operator absorbs any drift
	 * between create-time and runtime fees out of `escrow_fee`.
	 */
	ledger_fee_at_create: bigint;
}
export type DealStatus =
	| {
			/**
			 * A dispute is open on this deal. Funds remain in the escrow
			 * subaccount until the dispute resolves to `ArbitratedSettled` /
			 * `ArbitratedRefunded`. The expiry sweep (`services::expiry`)
			 * skips deals in this state.
			 */
			Disputed: null;
	  }
	| { Refunded: null }
	| {
			/**
			 * Dispute panel voted majority CC, OR both parties agreed
			 * out-of-band on a CC outcome — funds released to recipient.
			 * Distinct from `Settled` so callers can tell arbitrated from
			 * unilateral settlement. Terminal.
			 */
			ArbitratedSettled: null;
	  }
	| {
			/**
			 * Dispute panel voted majority IC, OR both parties agreed
			 * out-of-band on an IC outcome, OR the panel reached no quorum.
			 * Funds refunded to payer. Distinct from `Refunded`. Terminal.
			 */
			ArbitratedRefunded: null;
	  }
	| { Rejected: null }
	| { Funded: null }
	| { Cancelled: null }
	| { Created: null }
	| {
			/**
			 * Both parties signed `No` on a `Funded` bound deal — mutual
			 * agreement that the off-chain part of the deal did NOT happen.
			 * Funds returned to the payer using the same fee math as
			 * `Refunded` (`escrow_fee` retained, `ledger_fee` burned per
			 * transfer); the per-party dispute reserves are returned to
			 * each side. Distinct from `Refunded` (expiry-driven) and
			 * `ArbitratedRefunded` (dispute-driven) so the audit trail
			 * records WHY the deal didn't settle. Terminal.
			 */
			Aborted: null;
	  }
	| { Settled: null };
/**
 * Full deal view returned to authorised participants (payer or recipient).
 */
export interface DealView {
	/**
	 * Unique deal identifier.
	 */
	id: bigint;
	/**
	 * Current lifecycle status of the deal.
	 */
	status: DealStatus;
	/**
	 * Optional short title.
	 */
	title: [] | [string];
	/**
	 * Timestamp when the deal was funded, if applicable.
	 */
	funded_at_ns: [] | [bigint];
	/**
	 * Principal who last updated the deal.
	 */
	updated_by: [] | [Principal];
	/**
	 * Settlement asset for this deal. Today always
	 * [`Asset::Icrc`]; the enum exists so future settlement
	 * domains can be added without renaming this field.
	 */
	asset: Asset;
	/**
	 * Per-deal arbitrator panel size override chosen by the creator
	 * at `create_deal` time. `Some(n)` locks `n` arbitrators for
	 * any dispute on this deal; `None` means "use whatever
	 * `DisputeConfig.panel_size` is current when the dispute opens".
	 * Surfaced in the public view so a counterparty can see the
	 * committed dispute terms before consenting.
	 */
	panel_size: [] | [number];
	/**
	 * Recipient's consent to the deal terms.
	 */
	recipient_consent: Consent;
	/**
	 * Per-deal fee snapshot taken at `create_deal` time —
	 * `escrow_fee`, per-party dispute reserve, withdraw-fee
	 * percentage, and create-time ledger fee. Frontends should
	 * render these for transparent quoting (the recipient's
	 * expected payout is `amount - fees.escrow_fee - live ledger
	 * fee`).
	 */
	fees: DealFees;
	/**
	 * Timestamp when the deal was refunded, if applicable.
	 */
	refunded_at_ns: [] | [bigint];
	/**
	 * Optional note or message.
	 */
	note: [] | [string];
	/**
	 * Principal of the recipient, or `None` if not yet bound.
	 */
	recipient: [] | [Principal];
	/**
	 * Nanosecond UTC timestamp when the deal was last updated.
	 */
	updated_at_ns: [] | [bigint];
	/**
	 * 32-byte ledger subaccount that holds the escrowed funds.
	 */
	escrow_subaccount: Uint8Array;
	/**
	 * Principal who created the deal.
	 */
	created_by: Principal;
	/**
	 * Payer's consent to the deal terms.
	 */
	payer_consent: Consent;
	/**
	 * Recipient's settlement signature; mirrors
	 * [`Self::payer_signature`].
	 */
	recipient_signature: Signature;
	/**
	 * Nanosecond UTC timestamp when the deal was created.
	 */
	created_at_ns: bigint;
	/**
	 * Claim code for sharing via QR / link. Only visible to authorised
	 * participants; never exposed in the public claimable view.
	 */
	claim_code: [] | [string];
	/**
	 * Payer's settlement signature on a `Funded` bound deal —
	 * `Empty` until the payer calls `sign_yes` / `sign_no`. Tip
	 * flows (recipient unbound) always carry `Empty`. See
	 * [`Signature`] for tally semantics.
	 */
	payer_signature: Signature;
	/**
	 * Identifier of the attached dispute, if any. `Some(_)` while a
	 * dispute is open or after it has resolved (audit-trail link to
	 * the `Dispute` record); `None` for deals that never went into
	 * dispute.
	 */
	dispute: [] | [bigint];
	/**
	 * Timestamp when the deal was settled (funds released), if applicable.
	 */
	settled_at_ns: [] | [bigint];
	/**
	 * Principal of the payer, or `None` if not yet assigned.
	 */
	payer: [] | [Principal];
	/**
	 * Escrowed token amount.
	 */
	amount: bigint;
	/**
	 * Nanosecond UTC timestamp after which the deal expires.
	 */
	expires_at_ns: bigint;
}
/**
 * Admin-tunable dispute configuration. Lives nested in [`crate::types::state::Config`].
 *
 * All windows are nanoseconds (canister convention); fee bps follows the
 * standard ICRC bps convention (`10_000` = 100%).
 */
export interface DisputeConfig {
	/**
	 * Upper bound on the panel sizes a deal creator may request.
	 * Must be odd and `>= min_panel_size`. Bounds the cost (each
	 * extra arbitrator adds an ICRC-1 ledger fee at finalize) and
	 * the latency to fill the panel from the eligible pool.
	 */
	max_panel_size: number;
	/**
	 * Default number of arbitrators selected per dispute when the
	 * deal creator did not pick a per-deal `panel_size`. Must be odd
	 * and within `[min_panel_size, max_panel_size]`.
	 * `validation::validate_dispute_config` enforces all invariants
	 * when `update_config` is called.
	 */
	panel_size: number;
	/**
	 * Length of the Voting phase, in nanoseconds (default 2 days).
	 */
	voting_window_ns: bigint;
	/**
	 * Length of the Evidence phase, in nanoseconds (default 3 days).
	 */
	evidence_window_ns: bigint;
	/**
	 * Optional minimum arbitrator score required to be eligible for
	 * selection (Sybil filter). `None` = bootstrap mode (every active
	 * arbitrator is eligible; default).
	 */
	min_arbitrator_score: [] | [number];
	/**
	 * Minimum arbitration fee in the deal's token. The effective fee
	 * at `open_dispute` is `max(arbitration_min_fee, amount *
	 * arbitration_fee_bps / 10_000)`.
	 */
	arbitration_min_fee: bigint;
	/**
	 * Lower bound on the panel sizes a deal creator may request via
	 * `CreateDealArgs.panel_size`. Must be odd and `>= 3` (odd-only
	 * is required by the tally rules — no tie possible without an
	 * abstention; the `>= 3` floor is the smallest meaningful jury).
	 */
	min_panel_size: number;
	/**
	 * Arbitration fee in basis points of the disputed amount
	 * (default 500 = 5%). Combined with [`Self::arbitration_min_fee`].
	 */
	arbitration_fee_bps: number;
	/**
	 * Percentage of the arbitration fee paid to the panel when both
	 * parties resolve out-of-band via `withdraw_dispute` (default
	 * 25). `validation::validate_dispute_config` rejects values
	 * `> 100` at `update_config` time;
	 * `services::disputes::withdraw_finalize_locked` also clamps
	 * defensively at the use site so a hypothetical bad config that
	 * somehow slipped through (e.g. a future migration) can't
	 * over-pay arbitrators.
	 */
	withdraw_fee_pct: number;
}
/**
 * Outcome of a resolved dispute. Set on the `Dispute` record at finalize
 * time. The mapping to `DealStatus` is:
 *
 * | `DisputeOutcome`                                 | Resulting `DealStatus`     |
 * | ------------------------------------------------ | -------------------------- |
 * | `Settled { … }`                                  | `ArbitratedSettled`        |
 * | `Refunded { … }`                                 | `ArbitratedRefunded`       |
 * | `NoQuorum { … }`                                 | `ArbitratedRefunded` (no-quorum fallback) |
 * | `Withdrawn { agreed: ConcludedCorrectly }`       | `ArbitratedSettled`        |
 * | `Withdrawn { agreed: IncorrectlyConcluded }`     | `ArbitratedRefunded`       |
 */
export type DisputeOutcome =
	| {
			/**
			 * Majority IC — funds refunded to payer.
			 */
			Refunded: DisputeTally;
	  }
	| {
			/**
			 * Both parties agreed out-of-band on `agreed` via `withdraw_dispute`.
			 * Arbitrators receive the reduced `withdraw_fee_pct` slice of the fee.
			 */
			Withdrawn: { agreed: Vote };
	  }
	| {
			/**
			 * Voting deadline reached without enough non-abstain votes.
			 * Falls back to refunding the payer (status quo ante).
			 */
			NoQuorum: DisputeTally;
	  }
	| {
			/**
			 * Majority CC — funds released to recipient.
			 */
			Settled: DisputeTally;
	  };
/**
 * Lifecycle phase of a dispute. The phase advances on a strict timeline
 * driven by `evidence_deadline_ns` / `voting_deadline_ns` (set at
 * `open_dispute` time using the windows in [`DisputeConfig`]).
 */
export type DisputePhase =
	| {
			/**
			 * Evidence submission window. Both parties + arbitrators may post
			 * evidence; voting is closed.
			 */
			Evidence: null;
	  }
	| {
			/**
			 * Voting window. Evidence is frozen, arbitrators cast their votes.
			 */
			Voting: null;
	  }
	| {
			/**
			 * Tally finalised; outcome propagated to the parent `Deal`. Terminal.
			 */
			Resolved: null;
	  };
/**
 * Per-outcome vote counts. Mirrors the shape inside
 * `DisputeOutcome::Settled` / `Refunded` / `NoQuorum` so the public view
 * can surface counts independently of the `DisputeOutcome` discriminant.
 */
export interface DisputeTally {
	cc: number;
	ic: number;
	abstain: number;
}
/**
 * Full dispute view returned to authorised callers (parties of the
 * parent deal + arbitrators on the panel). Mirrors the shape of
 * [`crate::types::dispute::Dispute`] one-to-one for simplicity.
 */
export interface DisputeView {
	id: bigint;
	recipient_withdraw_proposal: [] | [Vote];
	opened_by: Principal;
	voting_deadline_ns: bigint;
	opened_at_ns: bigint;
	evidence: Array<Evidence>;
	arbitration_fee: bigint;
	panel: Array<PanelMember>;
	phase: DisputePhase;
	deal_id: bigint;
	payer_withdraw_proposal: [] | [Vote];
	evidence_deadline_ns: bigint;
	outcome: [] | [DisputeOutcome];
}
/**
 * Canonical error type returned by all deal endpoints.
 */
export type EscrowError =
	| {
			/**
			 * The deal has already reached a terminal state (`Settled`, `Refunded`, `Cancelled`, or
			 * `Rejected`).
			 */
			AlreadyFinalised: null;
	  }
	| {
			/**
			 * Payer and recipient cannot be the same principal.
			 */
			SelfDeal: null;
	  }
	| {
			/**
			 * At least one of payer or recipient must be specified.
			 */
			NeitherPartySet: null;
	  }
	| {
			/**
			 * The supplied expiry timestamp is invalid (e.g. in the past).
			 */
			InvalidExpiry: null;
	  }
	| {
			/**
			 * The anonymous principal cannot be used as a deal party.
			 */
			AnonymousParty: null;
	  }
	| {
			/**
			 * The supplied amount is invalid (e.g. zero).
			 */
			InvalidAmount: null;
	  }
	| {
			/**
			 * The requested dispute does not exist.
			 */
			DisputeNotFound: null;
	  }
	| {
			/**
			 * `create_deal` was called with an `amount` too small to
			 * cover the escrow fee + per-arbitrator ledger fees + the
			 * full dispute reserve, leaving zero or negative remainder
			 * for the recipient. The `min` field carries the **smallest
			 * acceptable amount** (i.e. one more than the rejected floor)
			 * so callers can retry with the reported value directly.
			 * Same convention as `AmountTooSmallForArbitration`.
			 */
			AmountBelowMinimum: { min: bigint };
	  }
	| {
			/**
			 * The payer principal is not set for this deal.
			 */
			PayerNotSet: null;
	  }
	| {
			/**
			 * The creator has not approved the escrow canister to pull
			 * the per-deal `creation_fee`, OR the ledger
			 * `icrc2_transfer_from` failed at create time. Returned by
			 * `create_deal` for any bound deal (recipient is `Some`). The
			 * half-formed deal is rolled forward to `Cancelled` so it
			 * doesn't sit as a stuck `Created` record. Tip flows
			 * (`recipient = None`) skip the `creation_fee` entirely and
			 * never emit this variant.
			 */
			CreationFeeRequired: null;
	  }
	| {
			/**
			 * The requested deal does not exist.
			 */
			NotFound: null;
	  }
	| {
			/**
			 * The arbitrator is `Suspended` or `Deregistered`.
			 */
			ArbitratorNotActive: null;
	  }
	| {
			/**
			 * `cast_vote` was called by a principal that is not on the
			 * dispute's selected panel.
			 */
			NotAssignedArbitrator: null;
	  }
	| {
			/**
			 * A generic validation error with a human-readable message.
			 */
			ValidationError: string;
	  }
	| {
			/**
			 * The caller is not authorised to perform this action on the deal.
			 */
			NotAuthorised: null;
	  }
	| {
			/**
			 * Both parties must consent before this operation can proceed.
			 */
			ConsentRequired: null;
	  }
	| {
			/**
			 * A claim code is required for open (unbound-recipient) deals.
			 */
			MissingClaimCode: null;
	  }
	| {
			/**
			 * An evidence submission exceeds the maximum allowed size for
			 * its field. Returned for both `note` overflow (limit
			 * `MAX_EVIDENCE_NOTE_LEN`) and `artefact_url` overflow (limit
			 * `MAX_EVIDENCE_URL_LEN`); the `max` field tells the caller
			 * WHICH limit was breached. Hash-length violations on
			 * `artefact_sha256` use `ValidationError` instead — those are
			 * shape checks ("must be exactly 32 bytes"), not size checks.
			 */
			EvidenceTooLarge: { max: number };
	  }
	| {
			/**
			 * An error occurred while communicating with the ICRC ledger canister.
			 */
			LedgerError: string;
	  }
	| {
			/**
			 * The caller has not approved the escrow canister to pull
			 * their `DC/2` dispute reserve, OR the ledger
			 * `icrc2_transfer_from` failed (insufficient funds /
			 * insufficient allowance). Returned by `consent_deal` for a
			 * bound-receiver deal and by `create_deal` when the receiver
			 * is the creator (3b). The deal stays `Created` so the caller
			 * can retry after approving.
			 */
			DisputeReserveRequired: null;
	  }
	| {
			/**
			 * The expiry timestamp is too far in the future.
			 */
			ExpiryTooFar: null;
	  }
	| {
			/**
			 * The caller's reliability score is below the minimum threshold.
			 */
			ReliabilityTooLow: { threshold: number; score: number };
	  }
	| {
			/**
			 * The supplied claim code does not match the deal's claim code.
			 */
			InvalidClaimCode: null;
	  }
	| {
			/**
			 * A metadata field exceeds its maximum allowed length.
			 */
			MetadataTooLong: { max: number; field: string };
	  }
	| {
			/**
			 * `open_dispute` was called on a deal whose `recipient` is `None`
			 * (open-recipient / tip-flow deal). Tip flows cannot be disputed
			 * because there is no bound counterparty in canister state.
			 */
			DisputeRequiresBoundRecipient: null;
	  }
	| {
			/**
			 * `open_dispute` was called on a deal that already has an open or
			 * resolved dispute attached.
			 */
			DisputeAlreadyExists: null;
	  }
	| {
			/**
			 * The caller does not match the deal's bound recipient.
			 */
			RecipientMismatch: null;
	  }
	| {
			/**
			 * The action requires the dispute to be in a different phase
			 * (`Evidence`, `Voting`, or `Resolved`).
			 */
			InvalidDisputePhase: {
				/**
				 * The phase the dispute is actually in.
				 */
				actual: string;
				/**
				 * The phase(s) that would have been valid.
				 */
				expected: string;
			};
	  }
	| {
			/**
			 * The ledger accepted the call but the transfer itself failed.
			 */
			TransferFailed: string;
	  }
	| {
			/**
			 * The caller has too many active (non-terminal) deals.
			 */
			TooManyActiveDeals: { max: number };
	  }
	| {
			/**
			 * `create_deal` was called with a `panel_size` outside the range
			 * `[DisputeConfig.min_panel_size, DisputeConfig.max_panel_size]`,
			 * or a value that is not odd.
			 *
			 * - `min` / `max` surface the active range so the caller can render the allowed window
			 * without parsing a free-form message.
			 * - `got` carries the value the caller sent so error logs are self-contained — clients don't
			 * need to correlate the rejection with the request payload to know which value was wrong,
			 * and a downstream `got` value of `4` (even, in-range) is distinguishable from `got = 11`
			 * (out-of-range) without re-checking the inputs.
			 */
			PanelSizeOutOfRange: { got: number; max: number; min: number };
	  }
	| {
			/**
			 * The eligible arbitrator pool is too small to fill the configured
			 * `panel_size`. Returned by `open_dispute` — the deal stays
			 * `Funded` so the caller can retry later or settle out-of-band.
			 */
			InsufficientArbitrators: { have: number; need: number };
	  }
	| {
			/**
			 * A reclaim was attempted before the deal's expiry deadline.
			 */
			NotExpired: null;
	  }
	| {
			/**
			 * The deal is not in the expected state for this operation.
			 */
			InvalidState: {
				/**
				 * The state the deal is actually in.
				 */
				actual: string;
				/**
				 * The state(s) that would have been valid.
				 */
				expected: string;
			};
	  }
	| {
			/**
			 * An accept was attempted after the deal's expiry deadline.
			 */
			Expired: null;
	  }
	| {
			/**
			 * The supplied `Asset` is not handled by the canister. Today
			 * this is unreachable: `Asset` only carries the `Icrc` variant
			 * and every code path that consumes an asset expects ICRC. The
			 * variant exists so future settlement domains (EVM ERC-20,
			 * native EVM, Solana SPL, …) added to `Asset` can surface a
			 * typed rejection at the boundary without bypassing the state
			 * machine — `Asset::as_icrc()` returns this variant for any
			 * non-ICRC asset, which means an integration that has its own
			 * `Asset` variant but lands a request against an ICRC-only
			 * service path gets a structured error instead of a silent
			 * mis-dispatch.
			 */
			UnsupportedAsset: null;
	  }
	| {
			/**
			 * `open_dispute` was called on a deal whose `amount` cannot cover
			 * the configured arbitration fee plus the per-arbitrator ICRC-1
			 * ledger fees. Tiny deals are not disputable.
			 */
			AmountTooSmallForArbitration: { min: bigint };
	  };
/**
 * A piece of evidence attached to a dispute.
 *
 * Artefacts are stored **off-canister**: the canister only
 * records a URL + SHA-256 commitment + an optional short note. Length
 * limits are enforced at the canister boundary; this struct itself is
 * purely a data carrier.
 */
export interface Evidence {
	submitted_at_ns: bigint;
	submitter: Principal;
	/**
	 * Free-form note (max 4 KiB at the boundary →
	 * [`EscrowError::EvidenceTooLarge`]).
	 */
	note: [] | [string];
	/**
	 * Off-canister artefact URL (max 2 KiB at the boundary).
	 */
	artefact_url: [] | [string];
	/**
	 * SHA-256 of the off-canister artefact. Always exactly 32 bytes when
	 * `Some` — the validator rejects other lengths.
	 */
	artefact_sha256: [] | [Uint8Array];
}
/**
 * Arguments for `finalize_dispute`.
 *
 * Anyone (non-anonymous) can call. Idempotent — calling again after
 * successful resolution returns the resolved view; calling when not
 * yet past `voting_deadline_ns` returns `InvalidDisputePhase`.
 */
export interface FinalizeDisputeArgs {
	dispute_id: bigint;
}
/**
 * Arguments for funding a created deal via ICRC-2 `transfer_from`.
 */
export interface FundDealArgs {
	/**
	 * Identifier of the deal to fund.
	 */
	deal_id: bigint;
}
export type GetClaimableDealResult = { Ok: ClaimableDealView } | { Err: EscrowError };
export type GetDealResult = { Ok: DealView } | { Err: EscrowError };
export type GetEscrowAccountResult = { Ok: Account } | { Err: EscrowError };
export type GetPublicDisputeResult = { Ok: PublicDisputeView } | { Err: EscrowError };
/**
 * ICRC-7 transfer argument for a single token.
 */
export interface Icrc7TransferArg {
	to: Account;
	token_id: bigint;
	memo: [] | [Uint8Array];
	from_subaccount: [] | [Uint8Array];
	created_at_time: [] | [bigint];
}
/**
 * ICRC-7 transfer error.
 */
export type Icrc7TransferError =
	| {
			GenericError: { message: string; error_code: bigint };
	  }
	| { Duplicate: { duplicate_of: bigint } }
	| { NonExistingTokenId: null }
	| { Unauthorized: null }
	| { CreatedInFuture: { ledger_time: bigint } }
	| { InvalidRecipient: null }
	| { GenericBatchError: { message: string; error_code: bigint } }
	| { TooOld: null };
/**
 * Explicit response variant for `icrc7_transfer` to avoid the generic
 * fallback name in the generated Candid interface.
 */
export type Icrc7TransferResponse = { Ok: bigint } | { Err: Icrc7TransferError };
/**
 * Pagination + filter arguments for `list_arbitrators`.
 */
export interface ListArbitratorsArgs {
	/**
	 * Filter by status. `None` returns all statuses.
	 */
	status: [] | [ArbitratorStatus];
	/**
	 * Number of arbitrators to skip (0-based). Defaults to `0`.
	 */
	offset: [] | [bigint];
	/**
	 * Maximum number of arbitrators to return. Defaults to `50`, capped
	 * at `100`.
	 */
	limit: [] | [bigint];
	/**
	 * Filter by minimum reliability score. Arbitrators with `score = None`
	 * are included only when `min_score` is `None`.
	 */
	min_score: [] | [number];
}
/**
 * Pagination arguments for listing the caller's deals.
 */
export interface ListMyDealsArgs {
	/**
	 * Number of deals to skip (0-based). Defaults to `0`.
	 */
	offset: [] | [bigint];
	/**
	 * Maximum number of deals to return. Defaults to `50`.
	 */
	limit: [] | [bigint];
}
/**
 * Pagination + filter arguments for `list_my_disputes`.
 */
export interface ListMyDisputesArgs {
	/**
	 * Number of disputes to skip (0-based). Defaults to `0`.
	 */
	offset: [] | [bigint];
	/**
	 * Maximum number of disputes to return. Defaults to `50`, capped
	 * at `100`.
	 */
	limit: [] | [bigint];
	/**
	 * Filter by phase. `None` returns disputes in all phases.
	 */
	phase: [] | [DisputePhase];
}
/**
 * One member of the dispute panel.
 *
 * Mirrors the `Deal.{funded_at_ns, funding_tx, settled_at_ns, payout_tx}`
 * pattern: `paid_at_ns` + `payout_tx` are populated when the per-arbitrator
 * fee transfer succeeds at finalize time, making the fan-out payout
 * replay-safe.
 */
export interface PanelMember {
	principal: Principal;
	/**
	 * `None` until the arbitrator calls `cast_vote` during the Voting phase.
	 */
	vote: [] | [Vote];
	/**
	 * ICRC-1 ledger block index of the per-arbitrator payout transfer.
	 */
	payout_tx: [] | [bigint];
	/**
	 * `None` until the arbitrator's slice of the arbitration fee has been
	 * successfully transferred via the ICRC-1 ledger at finalize.
	 */
	paid_at_ns: [] | [bigint];
}
export type ProcessExpiredDealsResult = { Ok: BigUint64Array } | { Err: EscrowError };
/**
 * Reduced public view for status pages.
 *
 * No party principals, no panel principals, no evidence URLs — just
 * the minimum any authenticated caller needs to render a dispute's
 * progress. Exposing the `deal_id` is intentional (it's already public
 * via the ICRC-7 token mapping); exposing the cc/ic/abstain counts
 * after resolution lets external indexers display tally summaries.
 */
export interface PublicDisputeView {
	id: bigint;
	/**
	 * Vote counts visible only after the dispute reaches `Resolved`
	 * (per phase-gated info disclosure). `None` while the dispute is
	 * still in `Evidence` / `Voting`.
	 */
	tally: [] | [DisputeTally];
	/**
	 * Number of arbitrators on the panel (no principals).
	 */
	panel_size: number;
	voting_deadline_ns: bigint;
	/**
	 * Number of evidence submissions (no URLs).
	 */
	evidence_count: number;
	phase: DisputePhase;
	deal_id: bigint;
	evidence_deadline_ns: bigint;
	/**
	 * Outcome — set when phase is `Resolved`.
	 */
	outcome: [] | [DisputeOutcome];
}
/**
 * Public view of a principal's reliability score.
 */
export interface ReliabilityView {
	/**
	 * Total concluded deals (positive + counterparty rejections).
	 */
	concluded: number;
	/**
	 * Reliability percentage (0–100), or `None` when there is not enough
	 * deal history to produce a meaningful score.
	 */
	score: [] | [number];
	/**
	 * Deals that ended positively (Settled or Refunded).
	 */
	positive: number;
}
/**
 * Per-party feedback signature recorded on a `Funded` bound deal.
 * Drives the settlement tally (see `services::deals::tally_signatures`).
 *
 * - `Empty`: no decision yet. Default for both parties when the deal becomes `Funded`. At expiry,
 * any `Empty` signature is treated as `Yes` for tally purposes (silence = release).
 * - `Yes`: the party affirms the deal completed correctly off-chain. Both parties on `Yes` →
 * `Settled` (release to recipient).
 * - `No`: the party affirms the deal did NOT complete correctly. Both parties on `No` → `Aborted`
 * (refund to payer). Mixed `Yes`/`No` → auto-`Disputed` (panel arbitration).
 *
 * Tip flows (`recipient = None`) never carry signatures: the tip
 * model has no bound counterparty to sign for, and signing endpoints
 * reject tip deals with `DisputeRequiresBoundRecipient`.
 */
export type Signature = { No: null } | { Yes: null } | { Empty: null };
/**
 * Arguments for `submit_evidence`.
 *
 * At least one of `note` / `(artefact_url + artefact_sha256)`
 * must be present; URL and hash are paired (one without the other is
 * rejected); `note` <= 4 KiB; `artefact_url` <= 2 KiB;
 * `artefact_sha256` exactly 32 bytes when set.
 */
export interface SubmitEvidenceArgs {
	/**
	 * Free-form note (max 4 KiB).
	 */
	note: [] | [string];
	/**
	 * Identifier of the dispute receiving the evidence.
	 */
	dispute_id: bigint;
	/**
	 * Off-canister artefact URL (max 2 KiB).
	 */
	artefact_url: [] | [string];
	/**
	 * SHA-256 of the off-canister artefact. Always exactly 32 bytes
	 * when `Some`.
	 */
	artefact_sha256: [] | [Uint8Array];
}
/**
 * ICRC-10 supported standard descriptor.
 */
export interface SupportedStandard {
	url: string;
	name: string;
}
/**
 * Outcome of `update_config`. `Ok` on successful validation +
 * persistence; `Err` carries the validation failure.
 */
export type UpdateConfigResult = { Ok: null } | { Err: EscrowError };
/**
 * Generic metadata value following the ICRC-16 specification.
 *
 * Used for both collection-level and token-level metadata in the ICRC-7 NFT
 * interface.
 */
export type Value =
	| { Int: bigint }
	| { Map: Vec }
	| { Nat: bigint }
	| { Blob: Uint8Array }
	| { Text: string }
	| { Array: Array<Value> };
export type Vec = Array<
	[
		string,
		(
			| { Int: bigint }
			| { Map: Vec }
			| { Nat: bigint }
			| { Blob: Uint8Array }
			| { Text: string }
			| { Array: Array<Value> }
		)
	]
>;
/**
 * A single arbitrator's vote on a dispute, or — at the canister boundary —
 * the outcome a party proposes via `withdraw_dispute`. The validator
 * at the boundary rejects `Abstain` for out-of-band proposals.
 */
export type Vote =
	| {
			/**
			 * "Incorrectly Concluded" — refund payer.
			 */
			IncorrectlyConcluded: null;
	  }
	| {
			/**
			 * Arbitrator abstained. Counts toward `disputes_assigned` but never
			 * toward `disputes_voted` / `disputes_with_majority` for the
			 * reliability score.
			 */
			Abstain: null;
	  }
	| {
			/**
			 * "Concluded Correctly" — release funds to recipient.
			 */
			ConcludedCorrectly: null;
	  };
/**
 * Arguments for `withdraw_dispute` — out-of-band settlement during
 * the Evidence phase.
 *
 * Caller must be `payer` or `recipient` of the parent deal. Allowed
 * during the `Evidence` phase only. `proposal: Some(_)` records the
 * caller's proposed outcome (latest-wins overwrite); `None` retracts.
 * `Some(Abstain)` is rejected. Resolution fires when both party
 * fields are `Some` and equal.
 */
export interface WithdrawDisputeArgs {
	dispute_id: bigint;
	proposal: [] | [Vote];
}
export interface _SERVICE {
	/**
	 * Accepts (claims) a funded deal, releasing the escrowed tokens to the caller.
	 *
	 * If the deal has no bound recipient, the caller must supply the correct
	 * `claim_code`. The caller is bound as the recipient and their consent is
	 * automatically set to `Accepted`. The deal transitions from `Funded` to
	 * `Settled`.
	 */
	accept_deal: ActorMethod<[AcceptDealArgs], AcceptDealResult>;
	/**
	 * Registers `args.principal` as an arbitrator. Curated registration —
	 * only canister controllers can add arbitrators to the pool.
	 *
	 * Idempotent: re-calling for an already-registered principal returns
	 * the existing profile (and reactivates it if it was `Suspended` or
	 * `Deregistered`). Score counters and `registered_at_ns` are
	 * preserved across reactivation; `registered_by` is updated to the
	 * calling controller.
	 */
	admin_register_arbitrator: ActorMethod<
		[AdminRegisterArbitratorArgs],
		AdminRegisterArbitratorResult
	>;
	/**
	 * Sets an arbitrator's status. All transitions are allowed (Active ↔
	 * Suspended ↔ Deregistered). Self-transitions are no-op success.
	 *
	 * Returns `EscrowError::NotFound` if the target principal isn't
	 * registered as an arbitrator.
	 */
	admin_set_arbitrator_status: ActorMethod<
		[AdminSetArbitratorStatusArgs],
		AdminRegisterArbitratorResult
	>;
	/**
	 * Returns the live `icrc1_balance_of` of the canister-owned
	 * treasury subaccount for the requested asset. Every bound deal's
	 * `creation_fee` accumulates here and stays until a controller
	 * drains it via `admin_treasury_withdraw`.
	 *
	 * This method is gated to canister controllers — the treasury
	 * balance is operationally sensitive (it reveals total accumulated
	 * anti-spam fees across all deals).
	 */
	admin_treasury_balance: ActorMethod<[AdminTreasuryBalanceArgs], AdminTreasuryBalanceResult>;
	/**
	 * Drains `amount` of `asset` from the treasury subaccount to
	 * `to` via `icrc1_transfer`. Returns the ledger block index on
	 * success.
	 *
	 * Caller is responsible for sizing `amount` against the live
	 * treasury balance — under-funded withdrawals surface as
	 * `EscrowError::TransferFailed` from the ledger.
	 *
	 * This method is gated to canister controllers.
	 */
	admin_treasury_withdraw: ActorMethod<[AdminTreasuryWithdrawArgs], AdminTreasuryBalanceResult>;
	/**
	 * Cancels a deal that has not yet been funded.
	 *
	 * Either party may cancel. The deal transitions from `Created` to
	 * `Cancelled`. Any reserves already deposited (the receiver's
	 * `DC/2` on a 3a deal where consent already moved money) are
	 * refunded; the operator retains its `escrow_fee` share when a
	 * reserve was on hand. Funded deals cannot be cancelled — use
	 * [`reclaim_deal`] after expiry instead.
	 */
	cancel_deal: ActorMethod<[CancelDealArgs], AcceptDealResult>;
	/**
	 * Casts a vote on a dispute. Caller must be on the panel and
	 * currently `Active`. Allowed only during the open voting window
	 * (`evidence_deadline_ns <= now < voting_deadline_ns`). Latest-wins
	 * semantics — calling repeatedly during the window updates the vote.
	 */
	cast_vote: ActorMethod<[CastVoteArgs], CastVoteResult>;
	/**
	 * Returns the current global configuration of the Escrow canister.
	 *
	 * This method is gated to canister controllers.
	 */
	config: ActorMethod<[], Config>;
	/**
	 * Explicitly consents to a deal's terms.
	 *
	 * The caller must be the payer or recipient. When called by the
	 * bound counterparty of a `Created` deal, `consent_deal` also
	 * performs the ICRC-2 deposit of that party's commit-at-first-action
	 * share into the deal subaccount:
	 *
	 * - 3a consenting recipient: pulls `DC/2` (approve at least `DC/2 + ledger_fee`).
	 * - 3b consenting payer: pulls `amount + DC/2` (approve at least `amount + DC/2 + ledger_fee`).
	 *
	 * Once both consents are recorded, the deal auto-flips from
	 * `Created` to `Funded` in the same call — there is no separate
	 * funding step.
	 */
	consent_deal: ActorMethod<[CancelDealArgs], AcceptDealResult>;
	/**
	 * Creates a new escrow deal.
	 *
	 * The caller is automatically assigned as one of the parties based on the
	 * supplied `payer` and `recipient` fields. Their consent is set to `Accepted`;
	 * the counterparty's consent starts as `Pending`.
	 *
	 * A cryptographically random claim code is generated and returned in the
	 * `DealView`. This code must be included in QR / share links so that an
	 * unbound recipient can later claim the deal.
	 */
	create_deal: ActorMethod<[CreateDealArgs], AcceptDealResult>;
	/**
	 * Self-deregisters the caller's arbitrator profile. Opt-out is a
	 * fundamental right that doesn't require admin intervention. The
	 * status flips to `Deregistered`; in-flight assignments are honoured
	 * (a non-vote then counts as `Vote::Abstain` at finalize time).
	 *
	 * To re-enter the pool the caller must be re-registered by an admin
	 * via `admin_register_arbitrator` — the curated registration model
	 * (admin chooses who's in) does not allow self-resurrection.
	 */
	deregister_arbitrator: ActorMethod<[], AdminRegisterArbitratorResult>;
	/**
	 * Force-finalises a dispute past its `voting_deadline_ns`. Anyone
	 * (non-anonymous) can call. Idempotent — replays after a successful
	 * finalize return the resolved view; partial replays (some
	 * arbitrator transfers succeeded, others trapped) skip already-paid
	 * panel members. Triggers tally + outcome propagation + ledger
	 * transfers + arbitrator score updates.
	 */
	finalize_dispute: ActorMethod<[FinalizeDisputeArgs], CastVoteResult>;
	/**
	 * Returns the arbitrator profile for `principal`, or `None` if the
	 * principal hasn't been registered. Public read; any non-anonymous
	 * caller may query any principal.
	 */
	get_arbitrator: ActorMethod<[Principal], [] | [ArbitratorProfile]>;
	/**
	 * Reduced public view for claim/share-link pages.
	 * Returns limited info (no payer, no claim code, no internal fields). Any
	 * authenticated caller may query this — authorization is intentionally open
	 * so a not-yet-bound recipient can preview the deal before accepting.
	 */
	get_claimable_deal: ActorMethod<[bigint], GetClaimableDealResult>;
	/**
	 * Returns the full deal view for an authorised participant.
	 *
	 * Only the payer or the bound recipient may query a deal's full details.
	 */
	get_deal: ActorMethod<[bigint], GetDealResult>;
	/**
	 * Returns the full dispute view. Caller must be a party of the parent
	 * deal or an arbitrator on the panel.
	 */
	get_dispute: ActorMethod<[bigint], CastVoteResult>;
	/**
	 * Returns the escrow `Account` (canister principal + deal subaccount) for a deal.
	 */
	get_escrow_account: ActorMethod<[bigint], GetEscrowAccountResult>;
	/**
	 * Returns a reduced public view of a dispute (no party / panel
	 * principals, no evidence URLs). Any non-anonymous caller may query.
	 */
	get_public_dispute: ActorMethod<[bigint], GetPublicDisputeResult>;
	/**
	 * Returns the reliability score for any principal.
	 *
	 * This is a public query — any authenticated caller may check any
	 * principal's score. No authorization required beyond being non-anonymous.
	 */
	get_reliability: ActorMethod<[Principal], ReliabilityView>;
	/**
	 * Returns the list of ICRC standards supported by this canister.
	 *
	 * Currently reports ICRC-7 (NFT) and ICRC-10 (supported-standards discovery).
	 */
	icrc10_supported_standards: ActorMethod<[], Array<SupportedStandard>>;
	/**
	 * Whether batch transfers are executed atomically. Currently `None`.
	 */
	icrc7_atomic_batch_transfers: ActorMethod<[], [] | [boolean]>;
	/**
	 * Returns the number of deal NFTs owned by each requested account.
	 *
	 * Accounts with a non-default subaccount always return `0`.
	 */
	icrc7_balance_of: ActorMethod<[Array<Account>], Array<bigint>>;
	/**
	 * Returns collection-level metadata as an ICRC-16 key-value map.
	 *
	 * Includes `icrc7:name`, `icrc7:symbol`, `icrc7:description`, and
	 * `icrc7:total_supply`.
	 */
	icrc7_collection_metadata: ActorMethod<[], Array<[string, Value]>>;
	/**
	 * Returns the default page size for `icrc7_tokens` / `icrc7_tokens_of`
	 * when the caller omits the `take` argument.
	 */
	icrc7_default_take_value: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns a human-readable description of the NFT collection.
	 */
	icrc7_description: ActorMethod<[], [] | [string]>;
	/**
	 * Returns the collection logo. Currently `None`.
	 */
	icrc7_logo: ActorMethod<[], [] | [string]>;
	/**
	 * Returns the maximum memo size accepted in transfer arguments.
	 *
	 * Currently `None` (no explicit limit).
	 */
	icrc7_max_memo_size: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the maximum number of token IDs accepted by `icrc7_token_metadata`
	 * and `icrc7_owner_of` in a single call.
	 */
	icrc7_max_query_batch_size: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the maximum page size for `icrc7_tokens` / `icrc7_tokens_of`.
	 */
	icrc7_max_take_value: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the maximum number of transfer args accepted by `icrc7_transfer`
	 * in a single call. Currently `None`.
	 */
	icrc7_max_update_batch_size: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the human-readable name of the NFT collection (`"Escrow Deals"`).
	 */
	icrc7_name: ActorMethod<[], string>;
	/**
	 * Returns the owner account for each requested token ID.
	 *
	 * Ownership follows deal lifecycle: the payer owns the token in all states
	 * except `Settled`, where the recipient becomes the owner.
	 * Unknown IDs produce `None`.
	 */
	icrc7_owner_of: ActorMethod<[Array<bigint>], Array<[] | [Account]>>;
	/**
	 * Returns the permitted time drift for deduplication. Currently `None`.
	 */
	icrc7_permitted_drift: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the maximum number of deal NFTs that can ever exist.
	 *
	 * Currently `None` (unlimited).
	 */
	icrc7_supply_cap: ActorMethod<[], [] | [bigint]>;
	/**
	 * Returns the ticker symbol of the NFT collection (`"ESCROW"`).
	 */
	icrc7_symbol: ActorMethod<[], string>;
	/**
	 * Returns per-token metadata for each requested token ID.
	 *
	 * Each deal's metadata includes `icrc7:name`, `escrow:status`,
	 * `escrow:payer`, `escrow:amount`, `escrow:asset_kind`,
	 * `escrow:asset`, and other deal-specific fields. ICRC deals
	 * additionally surface the bare ledger principal under the
	 * legacy `escrow:token_ledger` key for indexer back-compat.
	 * Unknown IDs produce `None` in the result vector.
	 */
	icrc7_token_metadata: ActorMethod<[Array<bigint>], Array<[] | [Array<[string, Value]>]>>;
	/**
	 * Returns a page of token IDs in ascending order.
	 *
	 * `prev` is the last token ID the caller received (exclusive cursor).
	 * `take` limits the page size (defaults to 50, capped at 500).
	 */
	icrc7_tokens: ActorMethod<[[] | [bigint], [] | [bigint]], Array<bigint>>;
	/**
	 * Returns a page of token IDs owned by `account`, in ascending order.
	 *
	 * See [`icrc7_tokens`] for cursor / take semantics.
	 */
	icrc7_tokens_of: ActorMethod<[Account, [] | [bigint], [] | [bigint]], Array<bigint>>;
	/**
	 * Returns the total number of deal NFTs that have been minted (one per deal).
	 */
	icrc7_total_supply: ActorMethod<[], bigint>;
	/**
	 * Rejects all transfer attempts with a `GenericError`.
	 *
	 * Deal ownership transitions are managed exclusively through escrow
	 * operations (`accept_deal`, `reclaim_deal`, …), not via direct ICRC-7
	 * transfers.
	 */
	icrc7_transfer: ActorMethod<[Array<Icrc7TransferArg>], Array<[] | [Icrc7TransferResponse]>>;
	/**
	 * Returns the transaction deduplication window. Currently `None`.
	 */
	icrc7_tx_window: ActorMethod<[], [] | [bigint]>;
	/**
	 * Lists registered arbitrators with optional `status` and `min_score`
	 * filters and pagination.
	 */
	list_arbitrators: ActorMethod<[ListArbitratorsArgs], Array<ArbitratorProfile>>;
	/**
	 * Lists all deals where the caller is either the payer or the recipient,
	 * ordered by creation time with pagination support.
	 */
	list_my_deals: ActorMethod<[ListMyDealsArgs], Array<DealView>>;
	/**
	 * Lists disputes the caller is involved with (party of the parent
	 * deal or arbitrator on the panel), reverse-chronological by
	 * `opened_at_ns`.
	 */
	list_my_disputes: ActorMethod<[ListMyDisputesArgs], Array<DisputeView>>;
	/**
	 * Opens a new dispute on a `Funded` deal. Caller must be `payer` or
	 * `recipient`. Funds remain in the escrow subaccount; the deal
	 * transitions `Funded → Disputed`. The expiry sweep skips
	 * `Disputed` deals.
	 */
	open_dispute: ActorMethod<[CancelDealArgs], CastVoteResult>;
	/**
	 * Batch-processes expired deals by refunding escrowed tokens back to their
	 * payers.
	 *
	 * Scans up to `limit` expired-but-still-funded deals and attempts to reclaim
	 * each one. Returns the IDs of deals that were successfully refunded.
	 */
	process_expired_deals: ActorMethod<[number], ProcessExpiredDealsResult>;
	/**
	 * Reclaims escrowed funds from an expired, unclaimed deal back to the payer.
	 *
	 * Only callable after the deal's `expires_at_ns` deadline has passed. The deal
	 * transitions from `Funded` to `Refunded`.
	 */
	reclaim_deal: ActorMethod<[CancelDealArgs], GetDealResult>;
	/**
	 * Rejects a deal's terms. The deal transitions to `Rejected` (terminal).
	 *
	 * The caller must be the payer or recipient. Their consent is set
	 * to `Rejected` and the deal becomes final. Any reserves already
	 * deposited are refunded; the operator retains its `escrow_fee`
	 * share when a reserve was on hand.
	 */
	reject_deal: ActorMethod<[CancelDealArgs], GetDealResult>;
	/**
	 * Records the caller's `No` settlement signature on a `Funded`
	 * bound deal and dispatches the resulting two-party tally:
	 *
	 * - other party also `No` → abort (refund to payer; new `Aborted` terminal).
	 * - other party `Yes` → auto-open a dispute.
	 * - other party still `Empty` → no-op; deal stays `Funded` with the new signature recorded.
	 *
	 * Same caller / tip / re-sign / post-expiry semantics as
	 * [`sign_yes`].
	 */
	sign_no: ActorMethod<[FundDealArgs], GetDealResult>;
	/**
	 * Records the caller's `Yes` settlement signature on a `Funded`
	 * bound deal and dispatches the resulting two-party tally:
	 *
	 * - other party also `Yes` → settle (release to recipient).
	 * - other party `No` → auto-open a dispute.
	 * - other party still `Empty` → no-op; deal stays `Funded` with the new signature recorded.
	 *
	 * Caller must be the bound payer or recipient. Tip flows
	 * (`recipient = None`) reject with `DisputeRequiresBoundRecipient`
	 * — use `accept_deal` (with the claim code) to claim a tip.
	 * While the deal is still `Funded`, re-signing overwrites the
	 * previous vote (latest-wins). At expiry the auto-YES rule (run by
	 * the housekeeping sweep) upgrades any unsigned party to `Yes`
	 * automatically; calling `sign_yes` after expiry returns `Expired`
	 * to make the transition explicit.
	 *
	 * Paired with [`sign_no`] — split into two endpoints (instead of
	 * a single `sign_deal(vote)`) to match the canister's
	 * `verb + deal_id` convention used by every other deal-action
	 * endpoint, and to make "sign with empty vote" unrepresentable
	 * at the Candid boundary.
	 */
	sign_yes: ActorMethod<[FundDealArgs], GetDealResult>;
	/**
	 * Submits a piece of evidence on a dispute. Caller must be a party
	 * of the parent deal or an arbitrator on the panel. Allowed during
	 * the `Evidence` phase only.
	 */
	submit_evidence: ActorMethod<[SubmitEvidenceArgs], CastVoteResult>;
	/**
	 * Updates the global configuration for the Escrow canister.
	 *
	 * Validates `config.dispute_config` against the invariants documented
	 * on `DisputeConfig` before persisting. Rejects with
	 * `EscrowError::ValidationError` on invalid input
	 * rather than letting bad config poison the dispute machinery at
	 * runtime (e.g. even `panel_size`, zero windows, fee bps > 100%).
	 *
	 * This method is gated to canister controllers.
	 */
	update_config: ActorMethod<[Config], UpdateConfigResult>;
	/**
	 * Out-of-band settlement during the Evidence phase. Caller must be
	 * `payer` or `recipient`. Records the caller's proposed outcome (or
	 * retracts on `proposal: None`); when both parties have proposed the
	 * same outcome, the dispute resolves with
	 * `DisputeOutcome::Withdrawn { agreed }`, the deal moves to
	 * `ArbitratedSettled` / `ArbitratedRefunded`, and arbitrators receive
	 * a reduced fee (`DisputeConfig::withdraw_fee_pct`).
	 */
	withdraw_dispute: ActorMethod<[WithdrawDisputeArgs], CastVoteResult>;
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
