/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

export const idlFactory = ({ IDL }) => {
	const Value = IDL.Rec();
	const Vec = IDL.Rec();
	const AcceptDealArgs = IDL.Record({
		claim_code: IDL.Opt(IDL.Text),
		deal_id: IDL.Nat64
	});
	const DealStatus = IDL.Variant({
		Disputed: IDL.Null,
		Refunded: IDL.Null,
		ArbitratedSettled: IDL.Null,
		ArbitratedRefunded: IDL.Null,
		Rejected: IDL.Null,
		Funded: IDL.Null,
		Cancelled: IDL.Null,
		Created: IDL.Null,
		Settled: IDL.Null
	});
	const Consent = IDL.Variant({
		Rejected: IDL.Null,
		Accepted: IDL.Null,
		Pending: IDL.Null
	});
	const DealView = IDL.Record({
		id: IDL.Nat64,
		status: DealStatus,
		title: IDL.Opt(IDL.Text),
		funded_at_ns: IDL.Opt(IDL.Nat64),
		updated_by: IDL.Opt(IDL.Principal),
		recipient_consent: Consent,
		refunded_at_ns: IDL.Opt(IDL.Nat64),
		note: IDL.Opt(IDL.Text),
		recipient: IDL.Opt(IDL.Principal),
		updated_at_ns: IDL.Opt(IDL.Nat64),
		escrow_subaccount: IDL.Vec(IDL.Nat8),
		created_by: IDL.Principal,
		payer_consent: Consent,
		created_at_ns: IDL.Nat64,
		claim_code: IDL.Opt(IDL.Text),
		dispute: IDL.Opt(IDL.Nat64),
		settled_at_ns: IDL.Opt(IDL.Nat64),
		payer: IDL.Opt(IDL.Principal),
		amount: IDL.Nat,
		token_ledger: IDL.Principal,
		expires_at_ns: IDL.Nat64
	});
	const EscrowError = IDL.Variant({
		AlreadyFinalised: IDL.Null,
		SelfDeal: IDL.Null,
		NeitherPartySet: IDL.Null,
		InvalidExpiry: IDL.Null,
		AnonymousParty: IDL.Null,
		InvalidAmount: IDL.Null,
		DisputeNotFound: IDL.Null,
		PayerNotSet: IDL.Null,
		NotFound: IDL.Null,
		ArbitratorNotActive: IDL.Null,
		NotAssignedArbitrator: IDL.Null,
		ValidationError: IDL.Text,
		NotAuthorised: IDL.Null,
		ConsentRequired: IDL.Null,
		MissingClaimCode: IDL.Null,
		EvidenceTooLarge: IDL.Record({ max: IDL.Nat32 }),
		LedgerError: IDL.Text,
		ExpiryTooFar: IDL.Null,
		ReliabilityTooLow: IDL.Record({
			threshold: IDL.Nat32,
			score: IDL.Nat32
		}),
		InvalidClaimCode: IDL.Null,
		MetadataTooLong: IDL.Record({ max: IDL.Nat32, field: IDL.Text }),
		DisputeRequiresBoundRecipient: IDL.Null,
		DisputeAlreadyExists: IDL.Null,
		RecipientMismatch: IDL.Null,
		InvalidDisputePhase: IDL.Record({
			actual: IDL.Text,
			expected: IDL.Text
		}),
		TransferFailed: IDL.Text,
		TooManyActiveDeals: IDL.Record({ max: IDL.Nat32 }),
		InsufficientArbitrators: IDL.Record({
			have: IDL.Nat32,
			need: IDL.Nat32
		}),
		NotExpired: IDL.Null,
		InvalidState: IDL.Record({ actual: IDL.Text, expected: IDL.Text }),
		Expired: IDL.Null,
		AmountTooSmallForArbitration: IDL.Record({ min: IDL.Nat })
	});
	const AcceptDealResult = IDL.Variant({
		Ok: DealView,
		Err: EscrowError
	});
	const AdminRegisterArbitratorArgs = IDL.Record({
		principal: IDL.Principal
	});
	const ArbitratorStatus = IDL.Variant({
		Deregistered: IDL.Null,
		Active: IDL.Null,
		Suspended: IDL.Null
	});
	const ArbitratorProfile = IDL.Record({
		status: ArbitratorStatus,
		principal: IDL.Principal,
		registered_at_ns: IDL.Nat64,
		disputes_assigned: IDL.Nat32,
		score: IDL.Opt(IDL.Nat32),
		disputes_voted: IDL.Nat32,
		disputes_with_majority: IDL.Nat32,
		registered_by: IDL.Principal
	});
	const AdminRegisterArbitratorResult = IDL.Variant({
		Ok: ArbitratorProfile,
		Err: EscrowError
	});
	const AdminSetArbitratorStatusArgs = IDL.Record({
		status: ArbitratorStatus,
		principal: IDL.Principal
	});
	const CancelDealArgs = IDL.Record({ deal_id: IDL.Nat64 });
	const Vote = IDL.Variant({
		IncorrectlyConcluded: IDL.Null,
		Abstain: IDL.Null,
		ConcludedCorrectly: IDL.Null
	});
	const CastVoteArgs = IDL.Record({ vote: Vote, dispute_id: IDL.Nat64 });
	const Evidence = IDL.Record({
		submitted_at_ns: IDL.Nat64,
		submitter: IDL.Principal,
		note: IDL.Opt(IDL.Text),
		artefact_url: IDL.Opt(IDL.Text),
		artefact_sha256: IDL.Opt(IDL.Vec(IDL.Nat8))
	});
	const PanelMember = IDL.Record({
		principal: IDL.Principal,
		vote: IDL.Opt(Vote),
		payout_tx: IDL.Opt(IDL.Nat),
		paid_at_ns: IDL.Opt(IDL.Nat64)
	});
	const DisputePhase = IDL.Variant({
		Evidence: IDL.Null,
		Voting: IDL.Null,
		Resolved: IDL.Null
	});
	const DisputeTally = IDL.Record({
		cc: IDL.Nat32,
		ic: IDL.Nat32,
		abstain: IDL.Nat32
	});
	const DisputeOutcome = IDL.Variant({
		Refunded: DisputeTally,
		Withdrawn: IDL.Record({ agreed: Vote }),
		NoQuorum: DisputeTally,
		Settled: DisputeTally
	});
	const DisputeView = IDL.Record({
		id: IDL.Nat64,
		recipient_withdraw_proposal: IDL.Opt(Vote),
		opened_by: IDL.Principal,
		voting_deadline_ns: IDL.Nat64,
		opened_at_ns: IDL.Nat64,
		evidence: IDL.Vec(Evidence),
		arbitration_fee: IDL.Nat,
		panel: IDL.Vec(PanelMember),
		phase: DisputePhase,
		deal_id: IDL.Nat64,
		payer_withdraw_proposal: IDL.Opt(Vote),
		evidence_deadline_ns: IDL.Nat64,
		outcome: IDL.Opt(DisputeOutcome)
	});
	const CastVoteResult = IDL.Variant({
		Ok: DisputeView,
		Err: EscrowError
	});
	const DisputeConfig = IDL.Record({
		panel_size: IDL.Nat32,
		voting_window_ns: IDL.Nat64,
		evidence_window_ns: IDL.Nat64,
		min_arbitrator_score: IDL.Opt(IDL.Nat32),
		arbitration_min_fee: IDL.Nat,
		arbitration_fee_bps: IDL.Nat32,
		withdraw_fee_pct: IDL.Nat32
	});
	const Config = IDL.Record({ dispute_config: IDL.Opt(DisputeConfig) });
	const CreateDealArgs = IDL.Record({
		title: IDL.Opt(IDL.Text),
		note: IDL.Opt(IDL.Text),
		recipient: IDL.Opt(IDL.Principal),
		payer: IDL.Opt(IDL.Principal),
		amount: IDL.Nat,
		token_ledger: IDL.Principal,
		expires_at_ns: IDL.Nat64
	});
	const FinalizeDisputeArgs = IDL.Record({ dispute_id: IDL.Nat64 });
	const FundDealArgs = IDL.Record({ deal_id: IDL.Nat64 });
	const FundDealResult = IDL.Variant({ Ok: DealView, Err: EscrowError });
	const ClaimableDealView = IDL.Record({
		id: IDL.Nat64,
		status: DealStatus,
		title: IDL.Opt(IDL.Text),
		note: IDL.Opt(IDL.Text),
		amount: IDL.Nat,
		token_ledger: IDL.Principal,
		expires_at_ns: IDL.Nat64,
		is_recipient_bound: IDL.Bool
	});
	const GetClaimableDealResult = IDL.Variant({
		Ok: ClaimableDealView,
		Err: EscrowError
	});
	const GetDealResult = IDL.Variant({ Ok: DealView, Err: EscrowError });
	const Account = IDL.Record({
		owner: IDL.Principal,
		subaccount: IDL.Opt(IDL.Vec(IDL.Nat8))
	});
	const GetEscrowAccountResult = IDL.Variant({
		Ok: Account,
		Err: EscrowError
	});
	const PublicDisputeView = IDL.Record({
		id: IDL.Nat64,
		tally: IDL.Opt(DisputeTally),
		panel_size: IDL.Nat32,
		voting_deadline_ns: IDL.Nat64,
		evidence_count: IDL.Nat32,
		phase: DisputePhase,
		deal_id: IDL.Nat64,
		evidence_deadline_ns: IDL.Nat64,
		outcome: IDL.Opt(DisputeOutcome)
	});
	const GetPublicDisputeResult = IDL.Variant({
		Ok: PublicDisputeView,
		Err: EscrowError
	});
	const ReliabilityView = IDL.Record({
		concluded: IDL.Nat32,
		score: IDL.Opt(IDL.Nat32),
		positive: IDL.Nat32
	});
	const SupportedStandard = IDL.Record({ url: IDL.Text, name: IDL.Text });
	Vec.fill(
		IDL.Vec(
			IDL.Tuple(
				IDL.Text,
				IDL.Variant({
					Int: IDL.Int,
					Map: Vec,
					Nat: IDL.Nat,
					Blob: IDL.Vec(IDL.Nat8),
					Text: IDL.Text,
					Array: IDL.Vec(Value)
				})
			)
		)
	);
	Value.fill(
		IDL.Variant({
			Int: IDL.Int,
			Map: Vec,
			Nat: IDL.Nat,
			Blob: IDL.Vec(IDL.Nat8),
			Text: IDL.Text,
			Array: IDL.Vec(Value)
		})
	);
	const Icrc7TransferArg = IDL.Record({
		to: Account,
		token_id: IDL.Nat,
		memo: IDL.Opt(IDL.Vec(IDL.Nat8)),
		from_subaccount: IDL.Opt(IDL.Vec(IDL.Nat8)),
		created_at_time: IDL.Opt(IDL.Nat64)
	});
	const Icrc7TransferError = IDL.Variant({
		GenericError: IDL.Record({
			message: IDL.Text,
			error_code: IDL.Nat
		}),
		Duplicate: IDL.Record({ duplicate_of: IDL.Nat }),
		NonExistingTokenId: IDL.Null,
		Unauthorized: IDL.Null,
		CreatedInFuture: IDL.Record({ ledger_time: IDL.Nat64 }),
		InvalidRecipient: IDL.Null,
		GenericBatchError: IDL.Record({
			message: IDL.Text,
			error_code: IDL.Nat
		}),
		TooOld: IDL.Null
	});
	const Icrc7TransferResponse = IDL.Variant({
		Ok: IDL.Nat,
		Err: Icrc7TransferError
	});
	const ListArbitratorsArgs = IDL.Record({
		status: IDL.Opt(ArbitratorStatus),
		offset: IDL.Opt(IDL.Nat64),
		limit: IDL.Opt(IDL.Nat64),
		min_score: IDL.Opt(IDL.Nat32)
	});
	const ListMyDealsArgs = IDL.Record({
		offset: IDL.Opt(IDL.Nat64),
		limit: IDL.Opt(IDL.Nat64)
	});
	const ListMyDisputesArgs = IDL.Record({
		offset: IDL.Opt(IDL.Nat64),
		limit: IDL.Opt(IDL.Nat64),
		phase: IDL.Opt(DisputePhase)
	});
	const ProcessExpiredDealsResult = IDL.Variant({
		Ok: IDL.Vec(IDL.Nat64),
		Err: EscrowError
	});
	const SubmitEvidenceArgs = IDL.Record({
		note: IDL.Opt(IDL.Text),
		dispute_id: IDL.Nat64,
		artefact_url: IDL.Opt(IDL.Text),
		artefact_sha256: IDL.Opt(IDL.Vec(IDL.Nat8))
	});
	const UpdateConfigResult = IDL.Variant({
		Ok: IDL.Null,
		Err: EscrowError
	});
	const WithdrawDisputeArgs = IDL.Record({
		dispute_id: IDL.Nat64,
		proposal: IDL.Opt(Vote)
	});

	return IDL.Service({
		accept_deal: IDL.Func([AcceptDealArgs], [AcceptDealResult], []),
		admin_register_arbitrator: IDL.Func(
			[AdminRegisterArbitratorArgs],
			[AdminRegisterArbitratorResult],
			[]
		),
		admin_set_arbitrator_status: IDL.Func(
			[AdminSetArbitratorStatusArgs],
			[AdminRegisterArbitratorResult],
			[]
		),
		cancel_deal: IDL.Func([CancelDealArgs], [AcceptDealResult], []),
		cast_vote: IDL.Func([CastVoteArgs], [CastVoteResult], []),
		config: IDL.Func([], [Config], ['query']),
		consent_deal: IDL.Func([CancelDealArgs], [AcceptDealResult], []),
		create_deal: IDL.Func([CreateDealArgs], [AcceptDealResult], []),
		deregister_arbitrator: IDL.Func([], [AdminRegisterArbitratorResult], []),
		finalize_dispute: IDL.Func([FinalizeDisputeArgs], [CastVoteResult], []),
		fund_deal: IDL.Func([FundDealArgs], [FundDealResult], []),
		get_arbitrator: IDL.Func([IDL.Principal], [IDL.Opt(ArbitratorProfile)], ['query']),
		get_claimable_deal: IDL.Func([IDL.Nat64], [GetClaimableDealResult], ['query']),
		get_deal: IDL.Func([IDL.Nat64], [GetDealResult], ['query']),
		get_dispute: IDL.Func([IDL.Nat64], [CastVoteResult], ['query']),
		get_escrow_account: IDL.Func([IDL.Nat64], [GetEscrowAccountResult], ['query']),
		get_public_dispute: IDL.Func([IDL.Nat64], [GetPublicDisputeResult], ['query']),
		get_reliability: IDL.Func([IDL.Principal], [ReliabilityView], ['query']),
		icrc10_supported_standards: IDL.Func([], [IDL.Vec(SupportedStandard)], ['query']),
		icrc7_atomic_batch_transfers: IDL.Func([], [IDL.Opt(IDL.Bool)], ['query']),
		icrc7_balance_of: IDL.Func([IDL.Vec(Account)], [IDL.Vec(IDL.Nat)], ['query']),
		icrc7_collection_metadata: IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, Value))], ['query']),
		icrc7_default_take_value: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_description: IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
		icrc7_logo: IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
		icrc7_max_memo_size: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_max_query_batch_size: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_max_take_value: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_max_update_batch_size: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_name: IDL.Func([], [IDL.Text], ['query']),
		icrc7_owner_of: IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(IDL.Opt(Account))], ['query']),
		icrc7_permitted_drift: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_supply_cap: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		icrc7_symbol: IDL.Func([], [IDL.Text], ['query']),
		icrc7_token_metadata: IDL.Func(
			[IDL.Vec(IDL.Nat)],
			[IDL.Vec(IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, Value))))],
			['query']
		),
		icrc7_tokens: IDL.Func([IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)], [IDL.Vec(IDL.Nat)], ['query']),
		icrc7_tokens_of: IDL.Func(
			[Account, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
			[IDL.Vec(IDL.Nat)],
			['query']
		),
		icrc7_total_supply: IDL.Func([], [IDL.Nat], ['query']),
		icrc7_transfer: IDL.Func(
			[IDL.Vec(Icrc7TransferArg)],
			[IDL.Vec(IDL.Opt(Icrc7TransferResponse))],
			[]
		),
		icrc7_tx_window: IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
		list_arbitrators: IDL.Func([ListArbitratorsArgs], [IDL.Vec(ArbitratorProfile)], ['query']),
		list_my_deals: IDL.Func([ListMyDealsArgs], [IDL.Vec(DealView)], ['query']),
		list_my_disputes: IDL.Func([ListMyDisputesArgs], [IDL.Vec(DisputeView)], ['query']),
		open_dispute: IDL.Func([FundDealArgs], [CastVoteResult], []),
		process_expired_deals: IDL.Func([IDL.Nat32], [ProcessExpiredDealsResult], []),
		reclaim_deal: IDL.Func([FundDealArgs], [GetDealResult], []),
		reject_deal: IDL.Func([FundDealArgs], [GetDealResult], []),
		submit_evidence: IDL.Func([SubmitEvidenceArgs], [CastVoteResult], []),
		update_config: IDL.Func([Config], [UpdateConfigResult], []),
		withdraw_dispute: IDL.Func([WithdrawDisputeArgs], [CastVoteResult], [])
	});
};

export const init = ({ IDL }) => {
	return [];
};
