name: Update E2E Snapshots

on:
  workflow_dispatch:

permissions: {}

jobs:
  update_snapshots:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Fail if branch is main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "This workflow should not be triggered on main"
          exit 1

      - name: Generate GitHub App token
        id: app-token
        if: vars.BOT_APP_ID != '' && vars.BOT_APP_INSTALLATION_ID != ''
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token || github.token }}
          persist-credentials: false

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Install Playwright
        uses: ./.github/actions/playwright-install

      - name: Run Playwright snapshot update
        run: npm run e2e:snapshots

      - name: Commit Playwright updated snapshots
        if: steps.app-token.outputs.token != ''
        uses: ./.github/actions/add-and-commit
        with:
          add: e2e
          message: '🤖 Update snapshots'
          token: ${{ steps.app-token.outputs.token }}
